import {CssBaseline} from "@mui/material";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import * as React from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body className={inter.className}><AppRouterCacheProvider>
            <CssBaseline/>
            {children}</AppRouterCacheProvider>
        </body>
        </html>
    );
}